### ISSUE TITLE
Feature required: Is there record for this tutorial?

### ISSUE THREAD

**Issue by Jack12xl** [InteractiveComputerGraphics/SPH-Tutorial#1]
Thanks for the splendid tutorial !
I noticed the video examples for the results in the slides. But I wonder if there exists record for the tutorial ?

**Comment by janbender** [comment]
What do you mean with "record"?

**Comment by Jack12xl** [comment]
If I understood it correctly, this repo contains the slides held in EG tutorial right? So I wonder whether the speaker's "record" for this tutorial was recorded 0.0

**Comment by janbender** [comment]
No, a record doesn't exist.

**Comment by Jack12xl** [comment]
What a pity though, I'm closing it now.
