### ISSUE TITLE
What does taking a gradient of the smoothing kernel (a scalar) in Eq.16 mean?

### ISSUE THREAD

**Issue by superdump** [InteractiveComputerGraphics/SPH-Tutorial#2]
In section 2.5 Discretization of Differential Operators, in the Difference Formula subsection, Eq.16 introduces &nabla;<sub>i</sub>W<sub>ij</sub>. I don't understand what the subscript i on the &nabla; means, and I don't understand how to apply the &nabla; gradient operator to a W<sub>ij</sub> which is scalar.

In section 2.3 Discretization, it is stated that W<sub>ij</sub> = W(**x**<sub>i</sub> - **x**<sub>j</sub>, h) and in section 2.2 Continuous Approximation, Eq.4 states W(**r**, h) is a product of &sigma;<sub>d</sub> which is scalar, and a function of q which is also scalar, and so W is also scalar.

What am I missing? Thank you for any help!

**Comment by superdump** [comment]
I found this in the code: https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/master/SPlisHSPlasH/SPHKernels.h#L510-L535

It seems, for 2D, to assume:

&nabla;<sub>i</sub>W<sub>ij</sub>=  6 &sigma;<sub>2</sub> f(q) **r** / (||**r**|| h)

Where f(q) is:
q(3q - 2) for 0 <= q <= 0.5
(q - 1)(1 - q) for 0.5 < q <= 1

I don't know where this comes from though, so I would still very much appreciate an explanation of why this is as it is. :)

**Comment by janbender** [comment]
∇iWij means that we differentiate with respect to x_i. So ∇i = ∂ /  ∂x_i.

The kernel is a scalar function. Hence, the gradient of the kernel is a vector.
