### ISSUE TITLE
Some confusion about multiphase flow in Eq.143?

### ISSUE THREAD

**Issue by CGrapher** [InteractiveComputerGraphics/SPH-Tutorial#3]
Dear authors, thank you very much for your excellent tutorial. I have learned a lot. Recently I'm studying multiphase flow. There was some confusion when reading the tutorial.
I consulted the literature [RLY* 14] and found that the mixture velocity given in the tutorial is inconsistent with the original article [RLY* 14]. May be my misunderstanding? I'm not sure about it.

The mixture velocity given in this tutorial:  \mathbf{v}_m = \frac{1}{\rho_m \sum_k {\alpha_k \rho_k \mathbf{v}_m}}

while that in [RLY* 14] is:  \mathbf{v}_m = \frac{1}{\rho_m} \sum_k {\alpha_k \rho_k \mathbf{v}_k}

**Comment by janbender** [comment]
Thanks for the comment. We will check this.

**Comment by janbender** [comment]
You are right. I just fixed the equation in the document. Thanks for pointing this out.
