### ISSUE TITLE
A_{ij} term clarification

### ISSUE THREAD

**Issue by hporro** [InteractiveComputerGraphics/SPH-Tutorial#5]
I think the term $A_{ij}$ in equations 22, 23, 24, 25 and 26 on the pdf refers to $A_i * A_j$ (because [Bro85] has a $T_i * T_j$ term instead), but it is not explicitly stated in the document. Maybe it would be good to clarify it in the pdf (and in the slides too), or I got it wrong? Is it a common abbreviation?

**Comment by janbender** [comment]
Hi, it seems that the explanation of A_ij is missing in the PDF. This means: A_ij = A_i - A_j (similar to Eq. 102). Brookshaw also defined it as difference (see e.g. Eq. 7 in the original paper), not as product. 

Thanks for reporting that we will update it in the PDF.

**Comment by hporro** [comment]
ok, thank you!
